# Generated by Django 3.0.5 on 2020-08-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('nombre', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstructuraNegocio.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstructuraNegocio.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('componenteEntrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canal_componenteEntrante', to='EstructuraNegocio.Componente')),
                ('componenteSaliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canal_componenteSaliente', to='EstructuraNegocio.Componente')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstructuraNegocio.Canal'),
        ),
    ]
