# Generated by Django 3.0.5 on 2020-08-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstructuraNegocio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canal',
            old_name='componenteEntrante',
            new_name='componente1',
        ),
        migrations.RenameField(
            model_name='canal',
            old_name='componenteSaliente',
            new_name='componente2',
        ),
    ]
