# Generated by Django 3.0.5 on 2020-08-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstructuraNegocio', '0003_auto_20200810_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
