# Generated by Django 3.0.5 on 2020-08-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('capacidad', models.FloatField(max_length=30)),
                ('estado', models.BooleanField(max_length=30)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioWeb',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('lenguaje', models.CharField(max_length=30)),
                ('urlAcceso', models.CharField(max_length=30)),
                ('sistemaOperativo', models.CharField(max_length=30)),
                ('tamanio', models.FloatField(max_length=30)),
                ('empaquetamiento', models.CharField(max_length=30)),
                ('politicaBackup', models.CharField(max_length=30)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='EntidadNegocio',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('aplicacionEntrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexion_aplicacionEntrante', to='aplicacion.Aplicacion')),
                ('aplicacionSaliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexion_aplicacionSaliente', to='aplicacion.Aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteTecnologico',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Conexion')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteApp',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='BaseDatos',
            fields=[
                ('id', models.BigIntegerField(default=None, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('capacidad', models.FloatField(max_length=30)),
                ('puerto', models.CharField(max_length=30)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aplicacion')),
            ],
        ),
    ]
