# Generated by Django 3.0.5 on 2020-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortafolioServicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='id',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicionegocio',
            name='id',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
        ),
    ]
