# Generated by Django 3.0.5 on 2020-08-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('rol', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('cardinalidad', models.CharField(max_length=30)),
                ('clase_entrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_claseEntrante', to='ModeloOntologico.Clase')),
                ('clase_saliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_claseSaliente', to='ModeloOntologico.Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('nombre', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModeloOntologico.Clase')),
            ],
        ),
    ]
